server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://${MESSAGES_DB_HOST:localhost}:5432/accessDb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        security: TRACE
