server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15433}/secretDb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        security: TRACE

app:
  link:
    scheme: http
    host: localhost
    port: ${APP_PORT:8090}