services:
  securedapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - securedApp
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - APP_PORT=8090

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=accessDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - securedApp
    ports:
      - 15432:5432


networks:
  securedApp:
    ipam:
      driver: default