version: "3.9"
services:
#  securedApp:
#    build:
#      context: .
#      dockerfile: .
#    ports:
#      - "8090:8090"
#    depends_on:
#      - postgres
#    networks:
#      - securedApp

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=accessDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - securedApp
    ports:
      - 5432:5432


networks:
  securedApp:
    ipam:
      driver: default