version: "3.9"
services:
  secretapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - postgres
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - APP_PORT=8091
    networks:
      - secretApp

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=secretDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - secretApp
    ports:
      - 15433:5432


networks:
  secretApp:
    ipam:
      driver: default